[package]
name = "rust-shell"
version = "0.1.0"
authors = ["Meet Parikh <meetparikh7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shlex = "0.1.1"
signal-hook = "0.3.6"
